name: Sync to Gitee
on:
  push:
    branches: [main]  # 监听指定分支的推送
  schedule:
    - cron: '0 */1 * * *'     # 每1小时同步一次（可选）
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # 拉取完整提交历史
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Mirror to Gitee
        run: |
          git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/yandashan666/awesome-deepseek-integration.git
          git push --all --force gitee
          git push --tags --force gitee
      - name: Full Mirror
        run: |
          git clone --bare https://github.com/deepseek-ai/awesome-deepseek-integration.git
          cd awesome-deepseek-integration.git
          gite remote add gitee https://${{ secrets.GITEE_TOKEN }}@gitee.com/yandashan666/awesome-deepseek-integration.git
          git push --mirror --force gitee
         # uses: Yikun/hub-mirror-action@master
         # with:
         #   src: github/yandashan/awesome-deepseek-integration
         #   dst: gitee/yandashan666/awesome-deepseek-integration
         #   dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
         #   dst_token: ${{ secrets.GITEE_TOKEN }}
         #   force_update: true
         #   debug: true
