name: Sync to Gitee
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0/8 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdir -p /home/runner/
          git config --global credential.helper 'store --file /home/runner/.git-credentials'
          # 确保此处凭据格式正确
          echo "https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com" > /home/runner/.git-credentials
      - name: Debug Credentials
        run: |
          cat /home/runner/.git-credentials
      - name: Mirror to Gitee
        run: |
          git remote add gitee https://gitee.com/${{ secrets.GITEE_USER }}/awesome-deepseek-integration.git
          git push --all --force gitee
          git push --tags --force gitee
